spring.application.name=order-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/orderService
spring.datasource.username=postgres
spring.datasource.password=20001231
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true







